version: "3"

services:
  php:
    container_name: agro-php
    build:
      context: docker
    volumes:
      - ${PWD}:/app
    working_dir: /app
    depends_on:
      - db
    restart: always
    networks:
      - agro-network
  db:
    container_name: agro-db
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - ${PG_PORT}:5432
    networks:
      - agro-network
    volumes:
      - agro-data:/var/lib/postgresql/data
  nginx:
    container_name: agro-nginx
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - ${PWD}/docker/conf.d:/etc/nginx/conf.d
      - ${PWD}/docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php
    restart: always
    networks:
      - agro-network
  node:
    container_name: agro-node
    image: node:alpine
    working_dir: /app
    volumes:
      - ${PWD}:/app
networks:
  agro-network:
    driver: bridge
volumes:
  agro-data:
